import { RowDataPacket } from "mysql2";

/**
 * User linking status enum
 */
export type UserLinkStatus =
  | "pending"
  | "processing"
  | "linked"
  | "expired"
  | "failed";

/**
 * Minecraft rank that can be synced to Discord roles
 */
export interface MinecraftRank {
  name: string;
  priority?: number;
}

/**
 * Database row structure for users table
 * Extends RowDataPacket for mysql2 compatibility
 */
export interface UserLinkRow extends RowDataPacket {
  /** Minecraft player UUID */
  uuid: string;
  /** Minecraft player username */
  minecraft_name: string;
  /** Discord user ID (snowflake) - null until linked */
  discord_id: string | null;
  /** Unique linking token generated by Minecraft plugin */
  token: string;
  /** Current status of the linking process */
  status: UserLinkStatus;
  /** JSON array of player ranks from Minecraft */
  ranks: string; // Stored as JSON string in MySQL
  /** Timestamp when the user was successfully linked */
  linked_at: Date | null;
  /**Timestamp when the token expires */
  token_expires_at: Date;
  /** Record creation timestamp */
  created_at: Date;
  /** Record last update timestamp */
  updated_at: Date;
}

/**
 * Parsed user data with typed ranks
 */
export interface UserLink {
  uuid: string;
  minecraftName: string;
  discordId: string | null;
  token: string;
  status: UserLinkStatus;
  ranks: MinecraftRank[];
  linkedAt: Date | null;
  tokenExpiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Update payload for linking a user
 */
export interface UserLinkUpdate {
  discordId: string;
  status: "linked";
  linkedAt: Date;
}

/**
 * Update payload for failed linking attempt
 */
export interface FailedUserLinkUpdate {
  status: "failed";
}
